spring:
  application:
    name: Springboot-ToDoList
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 465
    username: airplaneinmylove@gmail.com
    password: durw beoz oiwk qewj
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true

    